name: CI pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cheackout code
        uses: actions/checkout@v5
      
      - name: Set Up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: client-side
        run: npm install

      - name: Build project
        working-directory: client-side
        run: npm run build

     